version: '3'

networks:
  symfony:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
    - ./src:/var/www/html
    ports:
    - '9000:9000'
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - '8088:80'
    volumes:
    -  ./src:/var/www/html
    - ./nginx/default.conf:/etc/ngix/conf.d/default.conf

  postgresql:
    depends_on:
      - php
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - /path/to/postgresql-persistence/conf/:/bitnami/postgresql/conf/
    environment:
      - ./src/default.conf:/etc/ngix/conf.d/default.conf

  authapp:
    image: 'bitnami/symfony:1'
    ports:
      - '5432'
    volumes:
      - '.:/app'


